<%@ Page Language="C#" AutoEventWireup="true" MasterPageFile="~/Main.master" CodeBehind="Default.aspx.cs" Inherits="WebApplication._Default" %>


<asp:Content ID="Content" ContentPlaceHolderID="MainContent" runat="server">
    
    <dx:ASPxImageSlider ID="ASPxImageSlider1" runat="server" ImageSourceFolder="~\Content\Images\Slider\" Width="100%" ShowNavigationBar="False">
        <SettingsAutoGeneratedImages ImageCacheFolder="~/Thumb/" />
        <SettingsImageArea ImageSizeMode="FillAndCrop" NavigationButtonVisibility="Always" />
        <SettingsNavigationBar Mode="Dots" ItemSpacing="0" />
    </dx:ASPxImageSlider>
    
</asp:Content>